function createfigure(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 29-Jan-2023 14:05:32

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0322916666666667 0.541036717062635 0.953645833333332 0.434125269978396]);
hold(axes1,'on');

% Create plot
plot(Y1,'Parent',axes1);

% Create title
title('Figure with minimum correlation with j');

box(axes1,'on');
hold(axes1,'off');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.0338541666666667 0.0323974082073434 0.952604166666666 0.465442764578834]);
hold(axes2,'on');

% Create plot
plot(Y2,'Parent',axes2);

% Create title
title('Figure with minimum correlation with i');

box(axes2,'on');
hold(axes2,'off');
