function createfigure(Y1, Y2, order, corr, i, j)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 29-Jan-2023 15:09:46

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0229166666666667 0.501079913606912 0.966666666666666 0.431965442764579]);
hold(axes1,'on');

% Create plot
plot(Y1,'Parent',axes1);

box(axes1,'on');
hold(axes1,'off');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.0229166666666667 0.0248380129589633 0.966666666666666 0.444924406047513]);
hold(axes2,'on');

% Create plot
plot(Y2,'Parent',axes2);

box(axes2,'on');
hold(axes2,'off');
% Create sgtitle
titlename = strcat("Order: ",string(order), "  Correlation: ",string(corr), "  i: ",string(i), "  j: ", string(j));
sgtitle(figure1,titlename,...
    'FontWeight','bold',...
    'FontName','Times New Roman');

