function createfigure_of_GaussWin(Y1, titlename)
%CREATEFIGURE1(Y1)
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 31-Jan-2023 19:03:07

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.025 0.0669546436285097 0.95625 0.897408207343406]);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create title
title(titlename);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-21.3464055219663 220.653594478034]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.21405535626677 1.20594464373323]);
box(axes1,'on');
hold(axes1,'off');
